Traceback (most recent call last):
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\justb\anaconda3\envs\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\justb\anaconda3\envs\python37\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
square('circle')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-7-aafa7e540230>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0msquare[0m[1;33m([0m[1;34m'circle'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m<ipython-input-4-3e7f8c3e48a6>[0m in [0;36msquare[1;34m(n)[0m
[0;32m      1[0m [1;32mdef[0m [0msquare[0m[1;33m([0m[0mn[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m     [0mprint[0m[1;33m([0m[0mn[0m[1;33m**[0m[1;36m2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mTypeError[0m: unsupported operand type(s) for ** or pow(): 'str' and 'int'
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

